routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::domain('www.pasarpedia.id')->group(function(){
	Route::get('/','UtamaController@index')->name('utama.index');
	Route::post('/','UtamaController@store')->name('utama.store');
});

Route::get('login', 'AuthController@getLogin')->name('login');
Route::post('login', 'AuthController@postLogin')->name('login');
Route::get('register', 'AuthController@getRegister')->name('register');
Route::post('register', 'AuthController@postRegister')->name('register');
Route::get('logout', 'AuthController@getLogout')->name('logout')->middleware('auth');

// Auth::routes();

// Route::domain('apps.pasarpedia.id')->namespace('Apk')->group(function () {
Route::prefix('apps')->namespace('Apk')->group(function (){
	Route::get('/','IndexController@index')->name('apk.index');
	Route::get('cari','IndexController@cari')->name('apk.cari');
	Route::get('detail/{id}', 'IndexController@getDetail')->name('apk.detail');
	Route::get('member', 'IndexController@getMember')->name('apk.member')->middleware('auth');
	Route::get('member/profil', 'IndexController@getProfil')->name('apk.profil')->middleware('auth');
	Route::post('member/profil/update', 'IndexController@postProfil')->name('apk.profilUpdate')->middleware('auth');
	Route::post('member/profil/password', 'IndexController@postPassword')->name('apk.password')->middleware('auth');
	Route::get('member/keranjang', 'IndexController@getKeranjang')->name('apk.keranjang')->middleware('auth');
	Route::get('member/order', 'IndexController@getOrder')->name('apk.order')->middleware('auth');
	Route::get('member/order/{id}', 'IndexController@getOrderDetail')->name('apk.order-detail')->middleware('auth');
});

// Route::domain('{uid}.pasarpedia.id')->middleware('checkToko')->group(function () {
Route::prefix('u/{uid}')->middleware('checkToko')->group(function () {
    Route::get('/','IndexController@index')->name('index');
    Route::get('cari','IndexController@cari')->name('index.cari');
	Route::get('produk/{id}/{slug}', 'ProdukController@show')->name('produk.show');
	Route::resource('produk', 'ProdukController',['except' => [
	    'show'
	]]);
	Route::get('kategori/{id}/{slug}', 'KategoriController@show')->name('kategori.show');
	Route::get('promo', 'KategoriController@promo')->name('kategori.promo');
	Route::get('diskon', 'KategoriController@diskon')->name('kategori.diskon');
	Route::get('terlaris', 'KategoriController@terlaris')->name('kategori.terlaris');
	Route::get('terbaru', 'KategoriController@terbaru')->name('kategori.terbaru');

	Route::middleware('auth')->group(function(){
		Route::resource('order', 'OrderController');
		Route::post('keranjang/ubah/{id}', 'KeranjangController@ubah')->name('keranjang.ubah');
		Route::get('keranjang/antar', 'KeranjangController@antar')->name('keranjang.antar');
		Route::post('keranjang/bayar', 'KeranjangController@bayar')->name('keranjang.bayar');
		Route::post('keranjang/note', 'KeranjangController@postNote')->name('keranjang.note');
		Route::resource('keranjang', 'KeranjangController');
		Route::resource('newsToko', 'NewsController');
		Route::resource('member', 'MemberController',['except' => [
		    'show'
		]]);
		Route::get('member/profil', 'MemberController@profil')->name('member.profil');
		Route::get('member/toko', 'MemberController@toko')->name('member.toko');
		Route::post('member/profilUpdate', 'MemberController@profilUpdate')->name('member.profilUpdate');
		Route::post('member/password', 'MemberController@password')->name('member.password');
	});

	Route::get('orderanproses', 'IndexController@orderProses')->name('orderproses');
	Route::post('orderanproses', 'IndexController@postOrderProses');

});

// Route::prefix('admin')->namespace('Admin')->middleware('auth')->group(function () {
Route::prefix('admin')->namespace('Admin')->group(function (){
	Route::get('login', 'AuthController@index')->name('admin.index');
	Route::post('login', 'AuthController@auth')->name('admin.index');
	Route::post('logout', 'AuthController@logout')->name('admin.logout');
	Route::middleware('admin')->group(function(){
		Route::get('/','IndexController@index');
		Route::resource('beranda','IndexController');
		Route::resource('orderToko','OrderController');
		Route::get('toko/login/{id}', 'AuthController@toko')->name('toko.login');
		Route::get('toko/perpanjang','TokoController@perpanjang')->name('toko.perpanjang');
		Route::put('toko/perpanjang/aktifkan/{id}','TokoController@aktifkan')->name('toko.aktifkan');
		Route::put('toko/perpanjang/batalkan/{id}','TokoController@batalkan')->name('toko.batalkan');
		Route::get('toko/featured/{id}', 'TokoController@getFeatured')->name('toko.featured');
	    Route::resource('toko','TokoController');
	    Route::get('newsAdmin/tampil/{id}/{tampil}','NewsController@tampil')->name('newsAdmin.tampil');
	    Route::resource('newsAdmin','NewsController');
	    Route::resource('banks','BankController');
	    Route::resource('satuan','SatuanController');
	    Route::resource('slides','SlideController');
	    Route::resource('promos','PromoController');
	    Route::resource('information','InformationController');

	});
});

Route::prefix('tokoku')->namespace('AdminToko')->group(function (){
	Route::get('login', 'AuthController@index')->name('tokoku.index');
	Route::post('login', 'AuthController@auth')->name('tokoku.index');
	Route::get('reset-confirm', 'AuthController@reset2')->name('tokoku.reset2');
	Route::get('reset', 'AuthController@reset')->name('tokoku.reset');
	Route::post('reset', 'AuthController@resetact')->name('tokoku.reset');
	Route::post('lupa-password', 'AuthController@lupas')->name('tokoku.lupas');
	Route::post('logout', 'AuthController@logout')->name('tokoku.logout');

	Route::middleware('toko')->group(function(){
		Route::get('/','IndexController@index');
		Route::resource('dashboard','IndexController');
	    Route::resource('slide','SlideController');
	    Route::resource('cari','CariController');
	    Route::resource('kategori','KategoriController');
	    Route::resource('produk','ProdukController',['except' => [
		    'show'
		]]);
		Route::get('produk/gambar/{id}', 'ProdukController@gambar')->name('produk.gambar');
		Route::post('produk/gambarTambah/{id}', 'ProdukController@gambarTambah')->name('produk.storeGambar');
		Route::delete('produk/gambarHapus/{id}', 'ProdukController@gambarHapus')->name('produk.destroyGambar');
		
		Route::get('produk/stok/{id}', 'ProdukController@stok')->name('produk.stok');
		Route::post('produk/stokTambah/{id}', 'ProdukController@stokTambah')->name('produk.storeStok');
	    Route::resource('profil','ProfilController');
	    Route::resource('orderan','OrderanController');
	    Route::get('orderan/cetak/{id}','OrderanController@cetak')->name('orderan.cetak');
	    Route::get('orderan/cetak_besar/{id}','OrderanController@cetakbesar')->name('orderan.cetakbesar');
		Route::resource('memberku','MemberkuController');
		Route::get('memberku/login/{nohp}','AuthController@member')->name('memberku.login');
		Route::get('orderan/status/{status}', 'OrderanController@status')->name('orderan.status');
		Route::get('orderan/delete/{id}','OrderanController@getDelete')->name('orderan.delete');
	    Route::resource('laporan', 'LaporanController',['except' => [
		    'show'
		]]);
	    Route::get('laporan/perhari', 'LaporanController@perhari')->name('laporan.perhari');
	    Route::get('laporan/perbulan', 'LaporanController@perbulan')->name('laporan.perbulan');
	    Route::get('laporan/pertahun', 'LaporanController@pertahun')->name('laporan.pertahun');
	    Route::get('laporan/member', 'LaporanController@member')->name('laporan.member');
	    Route::get('news/tampil/{id}/{tampil}','NewsController@tampil')->name('news.tampil');
	    Route::resource('news','NewsController');
	    Route::resource('bank','BankController');
	    Route::resource('broadcast','BroadcastController');
	    Route::resource('referral','ReferralController');
	    Route::resource('metode','MethodController');
	    Route::resource('popup','PopupController');
	});
});

Route::prefix('referral')->namespace('Referral')->group(function (){
	Route::get('login','AuthController@login')->name('ref.login');
	Route::post('login','AuthController@loginact')->name('ref.login');
	Route::middleware('ref')->group(function(){
		Route::get('/','IndexController@index')->name('ref.index');
		Route::post('logout','AuthController@logout')->name('ref.logout');		
		Route::get('dashboard','IndexController@index')->name('ref.index');
		Route::get('member','MemberController@index')->name('ref.member');
		Route::get('transaksi','TransaksiController@index')->name('ref.transaksi');
		Route::get('transaksi/{date}','TransaksiController@perhari')->name('ref.transaksihari');
		Route::get('profil','ProfilController@index')->name('ref.profil');
		Route::put('profil/bank','ProfilController@bank')->name('ref.profilUpdateBank');
		Route::put('profil/pass','ProfilController@pass')->name('ref.profilUpdatePass');
	});
});

Route::get('/','UtamaController@index')->name('utama.index');
Route::post('/','UtamaController@store')->name('utama.store');

Route::get('clear_cache', function () {
    \Artisan::call('cache:clear');
    dd("Cache is cleared");
});

Route::get('test-email', function(){
	$order = \DB::table('otw_order')->first();
	\Mail::to('hendra.randy.nomura92@gmail.com')->send(new \App\Mail\KirimEmail($order));
});

app/Models/news.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class news extends Model
{
    //
    protected $table = "otw_news";
    protected $primaryKey = "id_news";

    protected $fillable = [
    	'judul',
    	'isi'
    ];

    protected $attributes = [
    	'tampil' => 0,
    	'hapus' => 0
    ];
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\news;

class NewsController extends Controller
{
    private $folder = "news/";

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $title = "Modul News :: Administrator";

        $news = news::where('hapus',0)->paginate(15);
        return view('admin/'.$this->folder.__FUNCTION__,compact('title','news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $title = "Modul News baru :: Administrator";

        return view('admin/'.$this->folder.__FUNCTION__,compact('title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'judul'=>'required',
            'isi'=>'required'
        ]);

        $news = new news([
            'judul'=>$request->get('judul'),
            'isi'=>$request->get('isi'),
        ]);
        $news->save();

        if($request->get('tampil')){
            $news->tampil = 1;
            $news->save();
        }

        return redirect('admin/news')->with('success','Berhasil menamahkan news baru');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $title = "Baca news :: Administrator";
        $news = news::find($id);

        return view('admin/'.$this->folder.__FUNCTION__,compact('title','news'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $title = "Modul News edit :: Administrator";
        $news = news::find($id);

        return view('admin/'.$this->folder.__FUNCTION__,compact('title','news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'judul'=>'required',
            'isi'=>'required'
        ]);

        $news = news::find($id);
        $news->judul = $request->get('judul');
        $news->isi = $request->get('isi');
        $news->save();

        return redirect('admin/news')->with('success','Berhasil mengubah news');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $news = news::find($id);
        $news->tampil = 0;
        $news->hapus = 1;
        $news->save();

        return redirect('admin/news')->with('success','Berhasil menghapus news');
    }

    public function tampil($id,$tampil){
        $news = news::find($id);
        $news->tampil = $tampil;
        $news->save();

        if($tampil > 0){
            return redirect('admin/news')->with('success','Berhasil menampilkan news');
        }else{
            return redirect('admin/news')->with('success','Berhasil menyembunyikan news');
        }
    }
}

app/Http/Controllers/AdminToko/AuthController.php
<?php

namespace App\Http\Controllers\AdminToko;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;

use Auth;
use App\Models\toko;
use App\Models\member;
use App\Mail\LupaPassword;

class AuthController extends Controller
{

    public function index(){
    	$title = "Login Dashboard Admin Toko";
    	return view('adminToko/auth/login',compact('title'));
    }

    public function auth(Request $request){

    	$username = $request->get('username');
    	$password = $request->get('password');

    	if (Auth::guard('toko')->attempt(['username' => $username, 'password' => $password ],true)) {
            return redirect('tokoku/dashboard');
		}else{
            return redirect('tokoku/login');
        }
    }

    public function lupas(Request $request){
        $title = "Lupa Password";

        $toko = toko::where('email',$request->get('email'))->first();

        if($toko){
            $respon['status'] = "success";
            $respon['pesan'] = "Permintaan sudah dikiriman ke email ".$request->get('email');

            Mail::to($request->get('email'))->send(new LupaPassword($request));
            $toko->resetpass = 1;
            $toko->save();

        }else{
            $respon['status'] = "danger";
            $respon['pesan'] = "Email tidak ditemukan";
        }
        return view('adminToko/auth/lupas',compact('title','respon'));
    }

    public function reset(Request $request){
        $title = "Reset Password";

        $email = base64_decode($request->get('s'));

        $now = date('Ymd');
        $reqDate = base64_decode($request->get('h'));

        $toko = toko::where('email', $email)->first();

        if($now == $reqDate && $toko && $toko->resetpass==1){
            $respon['status'] = 200;
        }else{
            $respon['status'] = 500;
        }

        return view('adminToko.auth.reset',compact('title','respon'));
    }

    public function resetact(Request $request){
        $request->validate([
            'password'=>'required|confirmed',
        ]);

        $email = base64_decode($request->get('s'));

        $toko = toko::where('email',$email)->first();
        $toko->password = \Hash::make($request->get('password'));
        $toko->password_text = $request->get('password');
        $toko->save();

        return redirect()->route('tokoku.reset2')->with('success','Password berhasil diganti');
    }

    public function reset2(){
        $title = "Reset Password";
        return view('adminToko.auth.reset2', compact('title'));
    }

    public function logout(){
        Auth::guard('toko')->logout();
        return redirect('tokoku/login');
    }

    public function member($nohp){
        $toko = toko::findOrFail(Auth::guard('toko')->id());
        $member = member::whereNohp($nohp)->whereIdToko($toko->id_toko)->first();

        try{
            if (Auth::guard('web')->attempt(['nohp' => $member->nohp, 'password' => $member->password_text], true)) {
                if(env('APP_ENV') == 'production')
                    return redirect()->to('https://'.$toko->username.'.pasarpedia.id');
                else{
                    return redirect('u/'.$toko->username);
                }
            }else{
                return 'error';
            }
        }catch(Exception $e){
            return $e->getMessage();
        }
        // return redirect()->to('https://'.$toko->username.'.pasarpedia.id');
    }
}

resources/views/adminToko/news/create.blade.php
@extends('adminToko.base')

@section('main')
<div class="container mt-3 mb-3">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Home</a></li>
	    <li class="breadcrumb-item"><a href="{{ route('news.index') }}">News</a></li>
	    <li class="breadcrumb-item active" aria-current="page">Baru</li>
	  </ol>
	</nav>

	<div class="row">
		<div class="col-md-12">
			@if($errors->count() > 0)
                <div class="alert alert-warning" role="alert">
                @foreach($errors->all() as $item)
                	<p>{{ $item }}</p>
                @endforeach
                </div>
            @endif
			<form method="POST" action="{{ route('news.store') }}" enctype="multipart/form-data">
			@csrf
				<div class="card mb-3">
					<div class="card-header">Form News Baru</div>
					<div class="card-body">
						<div class="form-group">
							<label for="judul">Judul</label>
							<input class="form-control" type="text" name="judul" id="judul" value="{{ old('judul') }}" required>
						</div>
						<div class="form-group">
							<label for="alamatp">Isi</label>
							<textarea class="form-control" type="text" name="isi" id="isi" required>{{ old('isi') }}</textarea>
						</div>
						<div class="form-group">
							<div class="form-check">
								<input class="form-check-input" type="checkbox" value="1" name="tampil" id="tampil">
								<label class="form-check-label" for="tampil">Tampil</label>
							</div>
						</div>
					</div>
				</div>
				<button type="submit" class="btn btn-sm btn-success">Simpan</button>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/adminToko/news/edit.blade.php
@extends('adminToko.base')

@section('main')
<div class="container mt-3 mb-3">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Home</a></li>
	    <li class="breadcrumb-item"><a href="{{ route('news.index') }}">News</a></li>
	    <li class="breadcrumb-item active" aria-current="page">Edit</li>
	  </ol>
	</nav>

	<div class="row">
		<div class="col-md-12">
			@if($errors->count() > 0)
                <div class="alert alert-warning" role="alert">
                @foreach($errors->all() as $item)
                	<p>{{ $item }}</p>
                @endforeach
                </div>
            @endif
			<form method="POST" action="{{ route('news.update',$newsToko->id_news) }}" enctype="multipart/form-data">
			@csrf
			@method('PUT')
				<div class="card mb-3">
					<div class="card-header">Form News Edit</div>
					<div class="card-body">
						<div class="form-group">
							<label for="judul">Judul</label>
							<input class="form-control" type="text" name="judul" id="judul" value="{{ $newsToko->judul }}" required>
						</div>
						<div class="form-group">
							<label for="alamatp">Isi</label>
							<textarea class="form-control" type="text" name="isi" id="isi" required>{{ $newsToko->isi }}</textarea>
						</div>
					</div>
				</div>
				<button type="submit" class="btn btn-sm btn-success">Simpan</button>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/adminToko/news/index.blade.php
@extends('adminToko.base')

@section('main')

<div class="container mt-3 mb-3">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Home</a></li>
	    <li class="breadcrumb-item active" aria-current="page">News</li>
	  </ol>
	</nav>

	@if(session()->get('success'))
    <div class="alert alert-success">
    	{{ session()->get('success') }}  
	</div>
    @endif

	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-body">
					<div class="table-responsive">
						<a href="{{ route('news.create') }}" class="btn btn-primary btn-sm mb-3" data-toggle="tooltip" title="Tambah news baru">News Baru <i class="fa fa-plus"></i></a>
						<h6><font size="2">* Fitur notifikasi ke member, untuk menyampaikan news, promo, diskon dll.</font></h6>
						<table class="table table-bordered">
							<thead>
								<tr>
									<th>Tanggal Dibuat</th>
									<th>Judul</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
							@forelse($newsToko as $item)
								<tr>
									<td>{{ tgl_indo($item->created_at) }}</td>
									<td>{{ $item->judul }}</td>
									<td>
										<a href="{{ route('news.show',$item->id_news) }}" data-toggle="tooltip" class="btn btn-info btn-sm" title="Detail news"><i class="fa fa-search"></i></a>
									</td>
								</tr>
							@empty
								<tr>
									<td colspan="4" align="center">Belum ada data</td>
								</tr>
							@endforelse
							</tbody>
						</table>
					</div>
					{{ $newsToko->links() }}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/adminToko/news/show.blade.php
@extends('adminToko.base')

@section('main')
<div class="container mt-3 mb-3">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Home</a></li>
	    <li class="breadcrumb-item"><a href="{{ route('news.index') }}">News</a></li>
	    <li class="breadcrumb-item active" aria-current="page">{{ $newsToko->judul }}</li>
	  </ol>
	</nav>

	<div class="row">
		<div class="col-md-12">
			<div class="card mb-3">
				<div class="card-header">{{ $newsToko->judul }}<a href="{{ route('news.edit', $newsToko) }}" class="float-right text-primary">Ubah</a></div>
				<div class="card-body">
					{!! $newsToko->isi !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection