routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::domain('www.pasarpedia.id')->group(function(){
	Route::get('/','UtamaController@index')->name('utama.index');
	Route::post('/','UtamaController@store')->name('utama.store');
});

Route::get('login', 'AuthController@getLogin')->name('login');
Route::post('login', 'AuthController@postLogin')->name('login');
Route::get('register', 'AuthController@getRegister')->name('register');
Route::post('register', 'AuthController@postRegister')->name('register');
Route::get('logout', 'AuthController@getLogout')->name('logout')->middleware('auth');

// Auth::routes();

// Route::domain('apps.pasarpedia.id')->namespace('Apk')->group(function () {
Route::prefix('apps')->namespace('Apk')->group(function (){
	Route::get('/','IndexController@index')->name('apk.index');
	Route::get('cari','IndexController@cari')->name('apk.cari');
	Route::get('detail/{id}', 'IndexController@getDetail')->name('apk.detail');
	Route::get('member', 'IndexController@getMember')->name('apk.member')->middleware('auth');
	Route::get('member/profil', 'IndexController@getProfil')->name('apk.profil')->middleware('auth');
	Route::post('member/profil/update', 'IndexController@postProfil')->name('apk.profilUpdate')->middleware('auth');
	Route::post('member/profil/password', 'IndexController@postPassword')->name('apk.password')->middleware('auth');
	Route::get('member/keranjang', 'IndexController@getKeranjang')->name('apk.keranjang')->middleware('auth');
	Route::get('member/order', 'IndexController@getOrder')->name('apk.order')->middleware('auth');
	Route::get('member/order/{id}', 'IndexController@getOrderDetail')->name('apk.order-detail')->middleware('auth');
});

// Route::domain('{uid}.pasarpedia.id')->middleware('checkToko')->group(function () {
Route::prefix('u/{uid}')->middleware('checkToko')->group(function () {
    Route::get('/','IndexController@index')->name('index');
    Route::get('cari','IndexController@cari')->name('index.cari');
	Route::get('produk/{id}/{slug}', 'ProdukController@show')->name('produk.show');
	Route::resource('produk', 'ProdukController',['except' => [
	    'show'
	]]);
	Route::get('kategori/{id}/{slug}', 'KategoriController@show')->name('kategori.show');
	Route::get('promo', 'KategoriController@promo')->name('kategori.promo');
	Route::get('diskon', 'KategoriController@diskon')->name('kategori.diskon');
	Route::get('terlaris', 'KategoriController@terlaris')->name('kategori.terlaris');
	Route::get('terbaru', 'KategoriController@terbaru')->name('kategori.terbaru');

	Route::middleware('auth')->group(function(){
		Route::resource('order', 'OrderController');
		Route::post('keranjang/ubah/{id}', 'KeranjangController@ubah')->name('keranjang.ubah');
		Route::get('keranjang/antar', 'KeranjangController@antar')->name('keranjang.antar');
		Route::post('keranjang/bayar', 'KeranjangController@bayar')->name('keranjang.bayar');
		Route::post('keranjang/note', 'KeranjangController@postNote')->name('keranjang.note');
		Route::resource('keranjang', 'KeranjangController');
		Route::resource('newsToko', 'NewsController');
		Route::resource('member', 'MemberController',['except' => [
		    'show'
		]]);
		Route::get('member/profil', 'MemberController@profil')->name('member.profil');
		Route::get('member/toko', 'MemberController@toko')->name('member.toko');
		Route::post('member/profilUpdate', 'MemberController@profilUpdate')->name('member.profilUpdate');
		Route::post('member/password', 'MemberController@password')->name('member.password');
	});

	Route::get('orderanproses', 'IndexController@orderProses')->name('orderproses');
	Route::post('orderanproses', 'IndexController@postOrderProses');

});

// Route::prefix('admin')->namespace('Admin')->middleware('auth')->group(function () {
Route::prefix('admin')->namespace('Admin')->group(function (){
	Route::get('login', 'AuthController@index')->name('admin.index');
	Route::post('login', 'AuthController@auth')->name('admin.index');
	Route::post('logout', 'AuthController@logout')->name('admin.logout');
	Route::middleware('admin')->group(function(){
		Route::get('/','IndexController@index');
		Route::resource('beranda','IndexController');
		Route::resource('orderToko','OrderController');
		Route::get('toko/login/{id}', 'AuthController@toko')->name('toko.login');
		Route::get('toko/perpanjang','TokoController@perpanjang')->name('toko.perpanjang');
		Route::put('toko/perpanjang/aktifkan/{id}','TokoController@aktifkan')->name('toko.aktifkan');
		Route::put('toko/perpanjang/batalkan/{id}','TokoController@batalkan')->name('toko.batalkan');
		Route::get('toko/featured/{id}', 'TokoController@getFeatured')->name('toko.featured');
	    Route::resource('toko','TokoController');
	    Route::get('newsAdmin/tampil/{id}/{tampil}','NewsController@tampil')->name('newsAdmin.tampil');
	    Route::resource('newsAdmin','NewsController');
	    Route::resource('banks','BankController');
	    Route::resource('satuan','SatuanController');
	    Route::resource('slides','SlideController');
	    Route::resource('promos','PromoController');
	    Route::resource('information','InformationController');

	});
});

Route::prefix('tokoku')->namespace('AdminToko')->group(function (){
	Route::get('login', 'AuthController@index')->name('tokoku.index');
	Route::post('login', 'AuthController@auth')->name('tokoku.index');
	Route::get('reset-confirm', 'AuthController@reset2')->name('tokoku.reset2');
	Route::get('reset', 'AuthController@reset')->name('tokoku.reset');
	Route::post('reset', 'AuthController@resetact')->name('tokoku.reset');
	Route::post('lupa-password', 'AuthController@lupas')->name('tokoku.lupas');
	Route::post('logout', 'AuthController@logout')->name('tokoku.logout');

	Route::middleware('toko')->group(function(){
		Route::get('/','IndexController@index');
		Route::resource('dashboard','IndexController');
	    Route::resource('slide','SlideController');
	    Route::resource('cari','CariController');
	    Route::resource('kategori','KategoriController');
	    Route::resource('produk','ProdukController',['except' => [
		    'show'
		]]);
		Route::get('produk/gambar/{id}', 'ProdukController@gambar')->name('produk.gambar');
		Route::post('produk/gambarTambah/{id}', 'ProdukController@gambarTambah')->name('produk.storeGambar');
		Route::delete('produk/gambarHapus/{id}', 'ProdukController@gambarHapus')->name('produk.destroyGambar');
		
		Route::get('produk/stok/{id}', 'ProdukController@stok')->name('produk.stok');
		Route::post('produk/stokTambah/{id}', 'ProdukController@stokTambah')->name('produk.storeStok');
	    Route::resource('profil','ProfilController');
	    Route::resource('orderan','OrderanController');
	    Route::get('orderan/cetak/{id}','OrderanController@cetak')->name('orderan.cetak');
	    Route::get('orderan/cetak_besar/{id}','OrderanController@cetakbesar')->name('orderan.cetakbesar');
		Route::resource('memberku','MemberkuController');
		Route::get('memberku/login/{nohp}','AuthController@member')->name('memberku.login');
		Route::get('orderan/status/{status}', 'OrderanController@status')->name('orderan.status');
		Route::get('orderan/delete/{id}','OrderanController@getDelete')->name('orderan.delete');
	    Route::resource('laporan', 'LaporanController',['except' => [
		    'show'
		]]);
	    Route::get('laporan/perhari', 'LaporanController@perhari')->name('laporan.perhari');
	    Route::get('laporan/perbulan', 'LaporanController@perbulan')->name('laporan.perbulan');
	    Route::get('laporan/pertahun', 'LaporanController@pertahun')->name('laporan.pertahun');
	    Route::get('laporan/member', 'LaporanController@member')->name('laporan.member');
	    Route::get('news/tampil/{id}/{tampil}','NewsController@tampil')->name('news.tampil');
	    Route::resource('news','NewsController');
	    Route::resource('bank','BankController');
	    Route::resource('broadcast','BroadcastController');
	    Route::resource('referral','ReferralController');
	    Route::resource('metode','MethodController');
	    Route::resource('popup','PopupController');
	});
});

Route::prefix('referral')->namespace('Referral')->group(function (){
	Route::get('login','AuthController@login')->name('ref.login');
	Route::post('login','AuthController@loginact')->name('ref.login');
	Route::middleware('ref')->group(function(){
		Route::get('/','IndexController@index')->name('ref.index');
		Route::post('logout','AuthController@logout')->name('ref.logout');		
		Route::get('dashboard','IndexController@index')->name('ref.index');
		Route::get('member','MemberController@index')->name('ref.member');
		Route::get('transaksi','TransaksiController@index')->name('ref.transaksi');
		Route::get('transaksi/{date}','TransaksiController@perhari')->name('ref.transaksihari');
		Route::get('profil','ProfilController@index')->name('ref.profil');
		Route::put('profil/bank','ProfilController@bank')->name('ref.profilUpdateBank');
		Route::put('profil/pass','ProfilController@pass')->name('ref.profilUpdatePass');
	});
});

Route::get('/','UtamaController@index')->name('utama.index');
Route::post('/','UtamaController@store')->name('utama.store');

Route::get('clear_cache', function () {
    \Artisan::call('cache:clear');
    dd("Cache is cleared");
});

Route::get('test-email', function(){
	$order = \DB::table('otw_order')->first();
	\Mail::to('hendra.randy.nomura92@gmail.com')->send(new \App\Mail\KirimEmail($order));
});

resources/views/admin/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

	<title>{{ $title }}</title>
    
	<link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.5.3/css/bootstrap-colorpicker.min.css">

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
</head>
<body style="padding-top: 0px !important;">

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container">
			<a class="navbar-brand" href="#">Admin</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active"><a class="nav-link" href="{{ route('beranda.index') }}">Home</a></li>
					<li class="nav-item"><a class="nav-link" href="{{ route('toko.index') }}">Toko</a></li>
					<li class="nav-item"><a class="nav-link" href="{{ route('newsAdmin.index') }}">News</a></li>
					<li class="nav-item"><a class="nav-link" href="{{ route('banks.index') }}">Bank</a></li>
					<li class="nav-item"><a class="nav-link" href="{{ route('satuan.index') }}">Satuan</a></li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="appsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Apps</a>
						<div class="dropdown-menu" aria-labelledby="appsDropdown">
							<a class="dropdown-item" href="{{ route('slides.index') }}">Slides</a>
							<a class="dropdown-item" href="{{ route('promos.index') }}">Promo</a>
							<a class="dropdown-item" href="{{ route('information.index') }}">Informasi</a>
						</div>
					</li>
					<li class="nav-item"><a class="nav-link" href="{{ route('toko.create') }}">Toko Baru</a></li>
				</ul>
				<ul class="navbar-nav navbar-right">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="profilDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin</a>
						<div class="dropdown-menu" aria-labelledby="profilDropdown">
							<!-- <div class="dropdown-divider"></div> -->
							<a class="dropdown-item" href="{{ route('admin.logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">Logout</a>
							<form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
								@csrf
							</form>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="container">
		@if(session()->has('success'))
		<div class="alert alert-success alert-dismissible fade show" role="alert">
			<strong>Success</strong> {{ session()->get('success') }}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		@endif

		@if(session()->has('error'))
		<div class="alert alert-danger alert-dismissible fade show" role="alert">
			<strong>Error</strong> {{ session()->get('error') }}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		@endif
	</div>

	@yield('main')
	
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.5.3/js/bootstrap-colorpicker.min.js"></script>

	<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
	<script src="https://cdn.ckeditor.com/4.14.1/full/ckeditor.js"></script>
	<script type="text/javascript">
	$(function(){
		$('.datatableBiasa').DataTable({
	        dom: 'Bfrtip',
	        buttons: [
	            'copyHtml5',
	            'excelHtml5',
	            'csvHtml5',
	            'pdfHtml5'
	        ]
	    });

	    $('.datatable').DataTable();
	    $('.ckeditor').each(function(){
			CKEDITOR.replace(this, {

			});
		});
	});
	</script>
	
	<script type="text/javascript">
		$(function() {
	        $('.cPicker').colorpicker();
	        $('[data-toggle="tooltip"]').tooltip();
	    });

	</script>
	<script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
	@yield('js')
</body>
</html>

resources/views/admin/beranda.blade.php
@extends('admin.base')

@section('main')
<div class="container mt-3">
	<div class="row mb-3">
		<div class="col-sm-6 col-md-3">
			<div class="card">
				<div class="card-body">
					Toko<br>
					{{ $toko->where('status',1)->count() }} Toko Aktif <br>
					{{ $toko->count() }} Total Toko 
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-md-3">
			<div class="card">
				<div class="card-body">
					Order<br>
					<a href="{{ route('orderToko.index') }}">{{ $orderToko->where('dilihat',0)->count() }}</a> Orderan Baru <br>
					{{ $orderToko->count() }} Total Orderan
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-md-3">
			<div class="card">
				<div class="card-body">
					Transaksi<br>
					{{ $order->count() }} Jumlah Transaksi<br>
					{{ rupiah($order->sum('total')) }} Total Transaksi
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-md-3">
			<div class="card">
				<div class="card-body">
					Ajuan Perpanjangan<br>
					<a href="{{ route('toko.perpanjang') }}">{{ $toko->where('perpanjang',1)->count() }} toko</a>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">10 Toko Terbaru</div>
				<div class="card-body">
					<div class="table-responsive">
						<table class="table">
							<thead>
								<tr>
									<th>Nama Toko</th>
									<th>Alamat Toko</th>
									<th>Kontak Toko</th>
								</tr>
							</thead>
							<tbody>
							@foreach($toko->sortByDesc('created_at') as $item)
								<tr>
									<td><a href="{{ route('toko.show',$item->id_toko) }}">{{ $item->nm_toko }}</a></td>
									<td>{{ $item->alamat_toko }}</td>
									<td>{{ $item->no_telp_toko }}</td>
								</tr>
							@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">10 Toko Expired dan Akan Expired</div>
				<div class="card-body">
					<div class="table-responsive">
						<table class="table">
							<thead>
								<tr>
									<th>Nama Toko</th>
									<th>Kontak Toko</th>
									<th>Expired</th>
								</tr>
							</thead>
							<tbody>
							@foreach($toko->where('status',0) as $item)
								<tr>
									<td><a href="{{ route('toko.show',$item->id_toko) }}">{{ $item->nm_toko }}</a></td>
									<td>{{ $item->no_telp_toko }}</td>
									<td><span class="btn btn-danger btn-sm">Expired</span></td>
								</tr>
							@endforeach
							@foreach($toko->where('status',1)->sortBy('aktif') as $item)
							<?php
								$mulai = $item->aktif;
								$oneYearOn = strtotime(date('Y-m-d H:i:s',strtotime($mulai . " + 1 year")));
								$now = time();
								$datediff = round(($oneYearOn - $now) / (60 * 60 * 24));
								if($datediff < 0){
									$datediff = 0;
								}
							?>
								<tr>
									<td><a href="{{ route('toko.show',$item->id_toko) }}">{{ $item->nm_toko }}</a></td>
									<td>{{ $item->no_telp_toko }}</td>
									@if($datediff > 0)
									<td><span class="btn btn-success btn-sm">{{ $datediff }} hari tersisa</span></td>
									@else
									<td><span class="btn btn-danger btn-sm">Expired</span></td>
									@endif
								</tr>
							@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>
@endsection