routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::domain('www.pasarpedia.id')->group(function(){
	Route::get('/','UtamaController@index')->name('utama.index');
	Route::post('/','UtamaController@store')->name('utama.store');
});

Route::get('login', 'AuthController@getLogin')->name('login');
Route::post('login', 'AuthController@postLogin')->name('login');
Route::get('register', 'AuthController@getRegister')->name('register');
Route::post('register', 'AuthController@postRegister')->name('register');
Route::get('logout', 'AuthController@getLogout')->name('logout')->middleware('auth');

// Auth::routes();

// Route::domain('apps.pasarpedia.id')->namespace('Apk')->group(function () {
Route::prefix('apps')->namespace('Apk')->group(function (){
	Route::get('/','IndexController@index')->name('apk.index');
	Route::get('cari','IndexController@cari')->name('apk.cari');
	Route::get('detail/{id}', 'IndexController@getDetail')->name('apk.detail');
	Route::get('member', 'IndexController@getMember')->name('apk.member')->middleware('auth');
	Route::get('member/profil', 'IndexController@getProfil')->name('apk.profil')->middleware('auth');
	Route::post('member/profil/update', 'IndexController@postProfil')->name('apk.profilUpdate')->middleware('auth');
	Route::post('member/profil/password', 'IndexController@postPassword')->name('apk.password')->middleware('auth');
	Route::get('member/keranjang', 'IndexController@getKeranjang')->name('apk.keranjang')->middleware('auth');
	Route::get('member/order', 'IndexController@getOrder')->name('apk.order')->middleware('auth');
	Route::get('member/order/{id}', 'IndexController@getOrderDetail')->name('apk.order-detail')->middleware('auth');
});

// Route::domain('{uid}.pasarpedia.id')->middleware('checkToko')->group(function () {
Route::prefix('u/{uid}')->middleware('checkToko')->group(function () {
    Route::get('/','IndexController@index')->name('index');
    Route::get('cari','IndexController@cari')->name('index.cari');
	Route::get('produk/{id}/{slug}', 'ProdukController@show')->name('produk.show');
	Route::resource('produk', 'ProdukController',['except' => [
	    'show'
	]]);
	Route::get('kategori/{id}/{slug}', 'KategoriController@show')->name('kategori.show');
	Route::get('promo', 'KategoriController@promo')->name('kategori.promo');
	Route::get('diskon', 'KategoriController@diskon')->name('kategori.diskon');
	Route::get('terlaris', 'KategoriController@terlaris')->name('kategori.terlaris');
	Route::get('terbaru', 'KategoriController@terbaru')->name('kategori.terbaru');

	Route::middleware('auth')->group(function(){
		Route::resource('order', 'OrderController');
		Route::post('keranjang/ubah/{id}', 'KeranjangController@ubah')->name('keranjang.ubah');
		Route::get('keranjang/antar', 'KeranjangController@antar')->name('keranjang.antar');
		Route::post('keranjang/bayar', 'KeranjangController@bayar')->name('keranjang.bayar');
		Route::post('keranjang/note', 'KeranjangController@postNote')->name('keranjang.note');
		Route::resource('keranjang', 'KeranjangController');
		Route::resource('newsToko', 'NewsController');
		Route::resource('member', 'MemberController',['except' => [
		    'show'
		]]);
		Route::get('member/profil', 'MemberController@profil')->name('member.profil');
		Route::get('member/toko', 'MemberController@toko')->name('member.toko');
		Route::post('member/profilUpdate', 'MemberController@profilUpdate')->name('member.profilUpdate');
		Route::post('member/password', 'MemberController@password')->name('member.password');
	});

	Route::get('orderanproses', 'IndexController@orderProses')->name('orderproses');
	Route::post('orderanproses', 'IndexController@postOrderProses');

});

// Route::prefix('admin')->namespace('Admin')->middleware('auth')->group(function () {
Route::prefix('admin')->namespace('Admin')->group(function (){
	Route::get('login', 'AuthController@index')->name('admin.index');
	Route::post('login', 'AuthController@auth')->name('admin.index');
	Route::post('logout', 'AuthController@logout')->name('admin.logout');
	Route::middleware('admin')->group(function(){
		Route::get('/','IndexController@index');
		Route::resource('beranda','IndexController');
		Route::resource('orderToko','OrderController');
		Route::get('toko/login/{id}', 'AuthController@toko')->name('toko.login');
		Route::get('toko/perpanjang','TokoController@perpanjang')->name('toko.perpanjang');
		Route::put('toko/perpanjang/aktifkan/{id}','TokoController@aktifkan')->name('toko.aktifkan');
		Route::put('toko/perpanjang/batalkan/{id}','TokoController@batalkan')->name('toko.batalkan');
		Route::get('toko/featured/{id}', 'TokoController@getFeatured')->name('toko.featured');
	    Route::resource('toko','TokoController');
	    Route::get('newsAdmin/tampil/{id}/{tampil}','NewsController@tampil')->name('newsAdmin.tampil');
	    Route::resource('newsAdmin','NewsController');
	    Route::resource('banks','BankController');
	    Route::resource('satuan','SatuanController');
	    Route::resource('slides','SlideController');
	    Route::resource('promos','PromoController');
	    Route::resource('information','InformationController');

	});
});

Route::prefix('tokoku')->namespace('AdminToko')->group(function (){
	Route::get('login', 'AuthController@index')->name('tokoku.index');
	Route::post('login', 'AuthController@auth')->name('tokoku.index');
	Route::get('reset-confirm', 'AuthController@reset2')->name('tokoku.reset2');
	Route::get('reset', 'AuthController@reset')->name('tokoku.reset');
	Route::post('reset', 'AuthController@resetact')->name('tokoku.reset');
	Route::post('lupa-password', 'AuthController@lupas')->name('tokoku.lupas');
	Route::post('logout', 'AuthController@logout')->name('tokoku.logout');

	Route::middleware('toko')->group(function(){
		Route::get('/','IndexController@index');
		Route::resource('dashboard','IndexController');
	    Route::resource('slide','SlideController');
	    Route::resource('cari','CariController');
	    Route::resource('kategori','KategoriController');
	    Route::resource('produk','ProdukController',['except' => [
		    'show'
		]]);
		Route::get('produk/gambar/{id}', 'ProdukController@gambar')->name('produk.gambar');
		Route::post('produk/gambarTambah/{id}', 'ProdukController@gambarTambah')->name('produk.storeGambar');
		Route::delete('produk/gambarHapus/{id}', 'ProdukController@gambarHapus')->name('produk.destroyGambar');
		
		Route::get('produk/stok/{id}', 'ProdukController@stok')->name('produk.stok');
		Route::post('produk/stokTambah/{id}', 'ProdukController@stokTambah')->name('produk.storeStok');
	    Route::resource('profil','ProfilController');
	    Route::resource('orderan','OrderanController');
	    Route::get('orderan/cetak/{id}','OrderanController@cetak')->name('orderan.cetak');
	    Route::get('orderan/cetak_besar/{id}','OrderanController@cetakbesar')->name('orderan.cetakbesar');
		Route::resource('memberku','MemberkuController');
		Route::get('memberku/login/{nohp}','AuthController@member')->name('memberku.login');
		Route::get('orderan/status/{status}', 'OrderanController@status')->name('orderan.status');
		Route::get('orderan/delete/{id}','OrderanController@getDelete')->name('orderan.delete');
	    Route::resource('laporan', 'LaporanController',['except' => [
		    'show'
		]]);
	    Route::get('laporan/perhari', 'LaporanController@perhari')->name('laporan.perhari');
	    Route::get('laporan/perbulan', 'LaporanController@perbulan')->name('laporan.perbulan');
	    Route::get('laporan/pertahun', 'LaporanController@pertahun')->name('laporan.pertahun');
	    Route::get('laporan/member', 'LaporanController@member')->name('laporan.member');
	    Route::get('news/tampil/{id}/{tampil}','NewsController@tampil')->name('news.tampil');
	    Route::resource('news','NewsController');
	    Route::resource('bank','BankController');
	    Route::resource('broadcast','BroadcastController');
	    Route::resource('referral','ReferralController');
	    Route::resource('metode','MethodController');
	    Route::resource('popup','PopupController');
	});
});

Route::prefix('referral')->namespace('Referral')->group(function (){
	Route::get('login','AuthController@login')->name('ref.login');
	Route::post('login','AuthController@loginact')->name('ref.login');
	Route::middleware('ref')->group(function(){
		Route::get('/','IndexController@index')->name('ref.index');
		Route::post('logout','AuthController@logout')->name('ref.logout');		
		Route::get('dashboard','IndexController@index')->name('ref.index');
		Route::get('member','MemberController@index')->name('ref.member');
		Route::get('transaksi','TransaksiController@index')->name('ref.transaksi');
		Route::get('transaksi/{date}','TransaksiController@perhari')->name('ref.transaksihari');
		Route::get('profil','ProfilController@index')->name('ref.profil');
		Route::put('profil/bank','ProfilController@bank')->name('ref.profilUpdateBank');
		Route::put('profil/pass','ProfilController@pass')->name('ref.profilUpdatePass');
	});
});

Route::get('/','UtamaController@index')->name('utama.index');
Route::post('/','UtamaController@store')->name('utama.store');

Route::get('clear_cache', function () {
    \Artisan::call('cache:clear');
    dd("Cache is cleared");
});

Route::get('test-email', function(){
	$order = \DB::table('otw_order')->first();
	\Mail::to('hendra.randy.nomura92@gmail.com')->send(new \App\Mail\KirimEmail($order));
});

app/Http/Controllers/AdminToko/AuthController.php
<?php

namespace App\Http\Controllers\AdminToko;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Mail;

use Auth;
use App\Models\toko;
use App\Models\member;
use App\Mail\LupaPassword;

class AuthController extends Controller
{

    public function index(){
    	$title = "Login Dashboard Admin Toko";
    	return view('adminToko/auth/login',compact('title'));
    }

    public function auth(Request $request){

    	$username = $request->get('username');
    	$password = $request->get('password');

    	if (Auth::guard('toko')->attempt(['username' => $username, 'password' => $password ],true)) {
            return redirect('tokoku/dashboard');
		}else{
            return redirect('tokoku/login');
        }
    }

    public function lupas(Request $request){
        $title = "Lupa Password";

        $toko = toko::where('email',$request->get('email'))->first();

        if($toko){
            $respon['status'] = "success";
            $respon['pesan'] = "Permintaan sudah dikiriman ke email ".$request->get('email');

            Mail::to($request->get('email'))->send(new LupaPassword($request));
            $toko->resetpass = 1;
            $toko->save();

        }else{
            $respon['status'] = "danger";
            $respon['pesan'] = "Email tidak ditemukan";
        }
        return view('adminToko/auth/lupas',compact('title','respon'));
    }

    public function reset(Request $request){
        $title = "Reset Password";

        $email = base64_decode($request->get('s'));

        $now = date('Ymd');
        $reqDate = base64_decode($request->get('h'));

        $toko = toko::where('email', $email)->first();

        if($now == $reqDate && $toko && $toko->resetpass==1){
            $respon['status'] = 200;
        }else{
            $respon['status'] = 500;
        }

        return view('adminToko.auth.reset',compact('title','respon'));
    }

    public function resetact(Request $request){
        $request->validate([
            'password'=>'required|confirmed',
        ]);

        $email = base64_decode($request->get('s'));

        $toko = toko::where('email',$email)->first();
        $toko->password = \Hash::make($request->get('password'));
        $toko->password_text = $request->get('password');
        $toko->save();

        return redirect()->route('tokoku.reset2')->with('success','Password berhasil diganti');
    }

    public function reset2(){
        $title = "Reset Password";
        return view('adminToko.auth.reset2', compact('title'));
    }

    public function logout(){
        Auth::guard('toko')->logout();
        return redirect('tokoku/login');
    }

    public function member($nohp){
        $toko = toko::findOrFail(Auth::guard('toko')->id());
        $member = member::whereNohp($nohp)->whereIdToko($toko->id_toko)->first();

        try{
            if (Auth::guard('web')->attempt(['nohp' => $member->nohp, 'password' => $member->password_text], true)) {
                if(env('APP_ENV') == 'production')
                    return redirect()->to('https://'.$toko->username.'.pasarpedia.id');
                else{
                    return redirect('u/'.$toko->username);
                }
            }else{
                return 'error';
            }
        }catch(Exception $e){
            return $e->getMessage();
        }
        // return redirect()->to('https://'.$toko->username.'.pasarpedia.id');
    }
}

app/Http/Controllers/AdminToko/BankController.php
<?php

namespace App\Http\Controllers\AdminToko;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\bank;
use App\Models\bankToko;
use Auth;
use Illuminate\Validation\Rule;

class BankController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = "Bank :: Administrator Toko";
        $bank = bank::where('tampil',1)->where('hapus',0)->get();
        $bankToko = bankToko::where('id_toko',Auth::guard('toko')->id())->where('hapus',0)->paginate(15);
        return view('adminToko.bank.index', compact('title','bank','bankToko'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = "Bank :: Administrator Toko";
        $bank = bank::where('tampil',1)->where('hapus',0)->get();
        return view('adminToko.bank.create', compact('title','bank'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'id_bank'=>['required', Rule::unique('otw_bank_toko')->where(function ($query) use($request) { return $query->where('id_bank', $request['id_bank'])->where('id_toko',Auth::guard('toko')->id()); })],
            'nama'=>'required',
            'norek'=>'required'
        ]);

        $bankToko = new bankToko([
            'id_bank'=>$request->get('id_bank'),
            'id_toko'=>Auth::guard('toko')->id(),
            'atas_nama'=>$request->get('nama'),
            'norek'=>$request->get('norek')
        ]);
        $bankToko->save();

        return redirect()->route('bank.index')->with('success','Berhasil menambahkan bank baru');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $title = "Edit Bank :: Administrator Toko";
        $bank = bank::where('tampil',1)->where('hapus',0)->get();
        $bankToko = bankToko::find($id);

        return view('adminToko.bank.edit',compact('title','bank','bankToko'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'bank'=>'required',
            'nama'=>'required',
            'norek'=>'required'
        ]);

        $bankToko = bankToko::find($id);
        $bankToko->id_bank = $request->get('bank');
        $bankToko->atas_nama = $request->get('nama');
        $bankToko->norek = $request->get('norek');
        $bankToko->save();

        return redirect()->route('bank.index')->with('success','Berhasil mengubah data bank');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $bankToko = bankToko::find($id);
        $bankToko->delete();

        return redirect()->route('bank.index')->with('success','Berhasil menghapus data bank');
    }
}

app/Http/Controllers/Referral/MemberController.php
<?php

namespace App\Http\Controllers\Referral;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\member;
use App\Models\order;
use Auth;

class MemberController extends Controller
{
    public function index(){

    	$member = member::where('ref', Auth::guard('ref')->user()->kode)->paginate(10);
    	$order = \DB::table('otw_order')->select(\DB::raw('otw_order.total, otw_order.id_member'))->where('otw_order.id_toko', Auth::guard('ref')->user()->id_toko)->where('bayar', 1)->get();
    	return view('referral.member.index', compact('member', 'order'));
    }
}

resources/views/adminToko/member/edit.blade.php
@extends('adminToko.base')

@section('main')
<div class="container mt-3 mb-3">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Home</a></li>
	    <li class="breadcrumb-item"><a href="{{ route('memberku.index') }}">MemberKu</a></li>
	    <li class="breadcrumb-item active" aria-current="page">{{ $member->nohp }}</li>
	  </ol>
	</nav>

	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">Ganti Password</div>
				<div class="card-body">
					<form action="{{ route('memberku.update', $member->id_member) }}" method="post">
					@csrf
					@method('PUT')
						<div class="form-group">
							<label>Password Baru</label>
							<input class="form-control" type="password" name="password" required min="6">
						</div>
						<div class="form-group">
							<label>Konfirmasi Password Baru</label>
							<input class="form-control" type="password" name="password_confirmation" required min="6">
						</div>
						<button type="submit" class="btn btn-success">Konfirmasi</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/adminToko/member/index.blade.php
@extends('adminToko.base')

@section('main')
<div class="container mt-3 mb-3">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Home</a></li>
	    <li class="breadcrumb-item active" aria-current="page">MemberKu</li>
	  </ol>
	</nav>

	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-bordered datatable">
							<thead>
								<tr>
									<th>Terdaftar</th>
									<th>Nomor Handphone</th>
									<th>Nama</th>
									<th>Alamat</th>
									<th>Total Pesanan</th>
									<th>Terakhir Pesan</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
							@forelse($member as $item)
								<tr>
									<td>{{ $item->created_at }}</td>
									<td>{{ $item->nohp }}</td>
									<td>{{ $item->nama }}</td>
									<td>{{ $item->alamat }}</td>
									<td class="text-right">{{ $item->jumlahOrder  }}</td>
									<td><?php echo $item->lastOrder?$item->lastOrder:'Belum order'; ?></td>
									<td>
										<a href="{{ route('memberku.show',$item->nohp) }}" class="btn btn-sm btn-primary">Detail</a>
										<a href="{{ route('memberku.edit',$item->nohp) }}" class="btn btn-sm btn-info">Ganti Password</a>
										<a href="{{ route('memberku.login',$item->nohp) }}" class="btn btn-sm btn-warning">Login</a>
									</td>
								</tr>
							@empty
								<tr>
									<td class="text-center" colspan="6">Belum Ada Member</td>
								</tr>
							@endforelse
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/adminToko/member/show.blade.php
@extends('adminToko.base')

@section('main')
<div class="container mt-3 mb-3">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Home</a></li>
	    <li class="breadcrumb-item"><a href="{{ route('memberku.index') }}">MemberKu</a></li>
	    <li class="breadcrumb-item active" aria-current="page">{{ $member->nohp }}</li>
	  </ol>
	</nav>

	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-body">
					<form method="get" action="" class="form-inline float-right">
						<input class="form-control date" type="text" name="from" id="from" value="{{ $date1 }}" placeholder="Mulai" required autocomplete="off">
						<input class="form-control date" type="text" name="until" id="until" value="{{ $date2 }}" placeholder="Sampai" required autocomplete="off">
						<button class="btn btn-success btn-lg" type="submit">Telusuri</button>
					</form>
					<div class="table-responsive">
						<table class="table table-bordered">
							<thead>
								<tr>
									<th>No Orderan</th>
									<th>Tanggal Pemesanan</th>
									<th>Status</th>
									<th>Jumlah Item</th>
									<th>Total Harga</th>
								</tr>
							</thead>
							<tbody>
							@forelse($order as $item)
								<tr>
									<td>{{ nopesan(Auth::guard('toko')->id(),$item->id_order,$item->created_at) }}</td>
									<td>{{ $item->created_at }}</td>
									<td>{{ ucfirst($item->status) }}</td>
									<td class="text-right">{{ $item->jumlahItem($item->id_order)->count() }}</td>
									<td class="text-right">{{ rupiah($item->total) }}</td>
								</tr>
							@empty
								<tr>
									<td colspan="5" class="text-center">Belum Ada Transaksi</td>
								</tr>
							@endforelse
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection